blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/decebal/dotfiles/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/decebal/dotfiles/blob/master/README.md
    about: Check out the comprehensive documentation
  - name: 🚀 Cool Plugins Guide
    url: https://github.com/decebal/dotfiles/blob/master/COOL-PLUGINS.md
    about: Learn about all the available plugins and features
