#! /bin/bash

export HISTTIMEFORMAT="%d/%m/%y %T "

alias ac="ack-grep"
alias apache_log="tail -f /var/log/apache2/*"
alias unix="date +%s"

alias grep="grep --color=auto"
alias tm="ps -ef | grep"

alias composer="php /usr/local/bin/composer"
alias cgetg="curl -s https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer"

# Git aliases
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gcl='git clone'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gm='git commit -m'
alias gma='git commit -am'
alias gp='git push'
alias gpu='git pull'
alias gpl='git pull'
alias gra='git remote add'
alias grr='git remote rm'
alias gs='git status'
alias gti="git"
alias pull="git pull -r"
alias up="git up"
alias push="up && git push"
alias diff="git difftool -b"

alias feature='git flow feature'
alias release='git flow release'
alias hotfix='git flow hotfix'

alias push-release="git co master; push --all; git co develop;"
alias gm_no_task="TASK=no gm"

alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'''

if [ -f $DOTFILES/local/aliases ]; then
	. $DOTFILES/local/aliases
fi

#TDD with php
alias phpspec='./vendor/bin/phpspec'
alias phpspecrun='./vendor/bin/phpspec run -fpretty -v'
alias phpunit='./vendor/bin/phpunit --testdox --colors'
alias behat='./vendor/bin/behat'
alias copy_ssh_key='xclip -sel clip < ~/.ssh/id_rsa.pub'

# Common shell aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias la='ls -la'
alias l='ls -l'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Docker aliases (if docker is available)
if command -v docker &>/dev/null; then
    alias d='docker'
    alias dc='docker-compose'
    alias dps='docker ps'
    alias dpsa='docker ps -a'
fi

# Homebrew aliases (if brew is available)
if command -v brew &>/dev/null; then
    alias bi='brew install'
    alias bs='brew search'
    alias bu='brew update && brew upgrade'
fi

# Python aliases (if python3 is available)
if command -v python3 &>/dev/null; then
    alias py='python3'
    alias pip='pip3'
fi

# Node.js aliases (if npm is available)
if command -v npm &>/dev/null; then
    alias ni='npm install'
    alias ns='npm start'
    alias nt='npm test'
    alias nr='npm run'
fi

