#! /bin/bash

export HISTTIMEFORMAT="%d/%m/%y %T "

alias ac="ack-grep"
alias apache_log="tail -f /var/log/apache2/*"
alias unix="date +%s"

alias grep="grep --color=auto"
alias tm="ps -ef | grep"

alias composer="php /usr/local/bin/composer"
alias cgetg="curl -s https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer"

alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gti="git"
alias pull="git pull -r"
alias up="git up"
alias push="up && git push"
alias gs="git status"
alias diff="git difftool -b"
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'

alias feature='git flow feature'
alias release='git flow release'
alias hotfix='git flow hotfix'

alias push-release="git co master; push --all; git co develop;"
alias gm_no_task="TASK=no gm"

alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'''

if [ -f $DOTFILES/local/aliases ]; then
	. $DOTFILES/local/aliases
fi

#TDD with php
alias phpspec='./vendor/bin/phpspec'
alias phpspecrun='./vendor/bin/phpspec run -fpretty -v'
alias phpunit='./vendor/bin/phpunit --testdox --colors'
alias behat='./vendor/bin/behat'
alias copy_ssh_key='xclip -sel clip < ~/.ssh/id_rsa.pub'

