#! /bin/bash

function lsmod() {
    ls -l | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'
}

function fetch() {
    git fetch origin "$1":"$@"; git co "$1";
}

function mcd() {
    mkdir -p "$1" && cd "$1";
}

if [ -f $DOTFILES/local/functions ]; then
	. $DOTFILES/local/functions
fi