#! /bin/bash

function lsmod() {
    ls -l | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));if(k)printf("%0o ",k);print}'
}

function fetch() {
    git fetch origin "$1":"$@"; git co "$1";
}

function mcd() {
    mkdir -p "$1" && cd "$1";
}
function deleteGitMerged() {
  git branch --merged | grep -v "\*" | xargs -n 1 git branch -d
}

function search() {
  if [ "$#" -gt "1" ]; then
    filetype="$1"
    search="$2"
  elif [ "$#" -eq "1" ]; then
    filetype="*"
    search="$1"
  else
    echo "Please provide function arguments.. use: search [filetype] regex "
    exit
  fi
  find . -iname "*.$filetype"|  grep -v "cache" | xargs grep "$search" 
}

function error_log() {
  domains=( 'ro' 'bg' 'hu' )

  if [ $# -eq 0 ]; then
    prefix="www"
  else
    prefix="$1"
  fi

  for d in "${domains[@]}"; do
    file="/var/log/apache2/${prefix}.emag.${d}-error.log"
    if [ -s $file ]; then
      break
    fi
  done
  if [ -r $file ]; then
    grc tail -f $file 
  fi
}

function access_log() {
  domains=( 'ro' 'bg' 'hu' )

  if [ $# -eq 0 ]; then
    prefix="www"
  else
    prefix="$1"
  fi

  for d in "${domains[@]}"; do
    file="/var/log/apache2/${prefix}.emag.${d}-access.log"
    echo $file
    if [ -f $file ]; then
      break
    fi
  done
  if [ -f $file ]; then
    tail -f $file | ccze
  fi
}

if [ -f $DOTFILES/local/functions ]; then
	. $DOTFILES/local/functions
fi

