#!/bin/zsh

ZSH=$DOTFILES/zsh/oh-my-zsh

if [ -f $DOTFILES/local/zsh-setup ]; then
	. $DOTFILES/local/zsh-setup
fi

if [ "$is_server" = true ]; then
    eval $(ssh-agent)
    /usr/bin/ssh-add
fi
zstyle :omz:plugins:ssh-agent agent-forwarding on

DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=false

if [ -z "$zsh_theme" ]; then
    ZSH_THEME="random"
else if [ "$zsh_theme" = 'powerline' ]
    #powerline configuration
    if [ -f $DOTFILES/common/powerline-zsh-config ]; then
    	. $DOTFILES/common/powerline-zsh-config
    fi
fi

export LS_OPTIONS='--color=auto'
COMPLETION_WAITING_DOTS="true"

if [ -f $DOTFILES/local/zsh-config ]; then
	. $DOTFILES/local/zsh-config
fi


plugins=(git gitfast rvm custom-aliases dircycle ssh-agent wd zsh-syntax-highlighting history history-substring-search colorize colored-man-pages autoenv debian emoji-clock pip python golang  direnv hook zsh-autosuggestions navi rust);
fpath=($DOTFILES/zsh-completions/src $fpath)

if [ -f $ZSH/oh-my-zsh.sh ]; then
    source $ZSH/oh-my-zsh.sh
fi

eval "$(direnv hook zsh)"

export EDITOR=vim
