#!/bin/zsh

ZSH=$DOTFILES/zsh/oh-my-zsh

if [ -f $DOTFILES/local/zsh-setup ]; then
	. $DOTFILES/local/zsh-setup
fi

if [ "$is_server" = true ]; then
    eval $(ssh-agent)
    /usr/bin/ssh-add
fi
zstyle :omz:plugins:ssh-agent agent-forwarding on

DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=false

if [ -z "$zsh_theme" ]; then
    ZSH_THEME="random"
else if [ "$zsh_theme" = 'powerline' ]
    #powerline configuration
    if [ -f $DOTFILES/common/powerline-zsh-config ]; then
    	. $DOTFILES/common/powerline-zsh-config
    fi
fi

export LS_OPTIONS='--color=auto'
COMPLETION_WAITING_DOTS="true"

if [ -f $DOTFILES/local/zsh-config ]; then
	. $DOTFILES/local/zsh-config
fi

#if [ -z "$zsh_plugins_list" ]; then
    #personal favorite plugins, may reduce the list to minimal, not just now
    #$zsh_plugin_list = "git gitfast rvm virtualenv composer custom-aliases dircycle ssh-agent sublime symfony2 wd ";
#fi

plugins=(git gitfast rvm virtualenv composer custom-aliases dircycle ssh-agent sublime symfony2 wd zsh-syntax-highlighting laravel history history-substring-search colorize colored-man-pages autoenv debian emoji-clock nyan pip python go);
fpath=($DOTFILES/zsh-completions/src $fpath)

if [ -f $ZSH/oh-my-zsh.sh ]; then
    source $ZSH/oh-my-zsh.sh
fi

#k git-zsh list directory plugin
if [ -f $DOTFILES/zsh/k/k.sh ]; then
    source $DOTFILES/zsh/k/k.sh
fi

# Change directory on login
# if [[ -o login ]]; then
#     cd /var/www
# fi
