#!/bin/zsh
#Path to your oh-my-zsh configuration.

DOTFILES=$HOME/.dotfiles
ZSH=$DOTFILES/zsh/oh-my-zsh
zsh_theme="powerline"

if [ -f $DOTFILES/local/master-config.sh ]; then
	. $DOTFILES/local/master-config.sh
fi

# Customize to your needs...
if [ -f $DOTFILES/common/paths ]; then
	. $DOTFILES/common/paths
fi

if [ -f $DOTFILES/common/zsh-config ]; then
	. $DOTFILES/common/zsh-config
fi

# Alias definitions.
    if [ -f $DOTFILES/common/aliases ]; then
    . $DOTFILES/common/aliases
    fi

    if [ -f $DOTFILES/common/functions ]; then
        . $DOTFILES/common/functions
    fi


umask 0000
export TERM="xterm-256color"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
