# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export DOTFILES=$HOME/.dotfiles
DOTFILES=$HOME/.dotfiles

VIRTUALENVWRAPPER_PYTHON=/usr/bin/python

#osx color terminal
export CLICOLOR=1
# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Alias definitions.
    if [ -f $DOTFILES/common/aliases ]; then
    . $DOTFILES/common/aliases
    fi

    if [ -f $DOTFILES/common/functions ]; then
        . $DOTFILES/common/functions
    fi

    if [ -f $DOTFILES/bash/git_completion.bash ]; then
        . $DOTFILES/bash/git_completion.bash
    fi

    if [ -f $DOTFILES/bash/git-flow-completion.bash ]; then
        . $DOTFILES/bash/git-flow-completion.bash
    fi

    if [ -f $DOTFILES/bash/symfony2-autocomplete.bash ]; then
        . $DOTFILES/bash/symfony2-autocomplete.bash
    fi

    if [ -f $DOTFILES/bash/complete-hosts.sh ]; then
        . $DOTFILES/bash/complete-hosts.sh
    fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
        . /etc/bash_completion
    fi
# Set $TERM for libvte terminals that set $TERM wrong (like gnome-terminal)
{
    [ "_$TERM" = "_xterm" ] && type ldd && type grep && type tput && [ -L "/proc/$PPID/exe" ] && {
        if ldd /proc/$PPID/exe | grep libvte; then
            if [ "`tput -Txterm-256color colors`" = "256" ]; then
                TERM=xterm-256color
            elif [ "`tput -Txterm-256color colors`" = "256" ]; then
                TERM=xterm-256color
            elif tput -T xterm; then
                TERM=xterm
            fi
        fi
    }
} >/dev/null 2>/dev/null

cd /var/www

export PATH=$PATH:~/bin
umask 0000

source $DOTFILES/bash/git.bashrc
